# Generated by Django 4.1.2 on 2022-11-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('price_cents', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('volume_discount_percent', models.IntegerField(null=True)),
                ('volume_discount_threshold', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
