# Generated by Django 4.1.2 on 2022-11-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
