# Generated by Django 4.1.2 on 2022-11-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
