# Generated by Django 4.1.2 on 2022-11-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
    ]
